testcase:
  userId: 2003100795
databuild:
  host: http://data-build.test.91gfd.cn
loan-clearing:
  new:
    host: http://clearing-gateway24.test.91gfd.cn
  old:
    host: http://loan-clearing.test.91gfd.cn
payment:
  trade:
    host: http://trade21.test.91gfd.cn
accounting:
  host: http://accounting24.test.91gfd.cn
superdiamond:
  host: http://superdiamond.test.91gfd.cn
  account:
    userCode: admin
    password: '000000'
mq:
  host: http://mq.test.91gfd.cn
