testcase:
  userId: 2003100795
databuild:
  host: http://data-build.test.91gfd.cn
loan-clearing:
  new:
    host: http://clearing-gateway.test.91gfd.cn
  old:
    host: http://loan-clearing41.test.91gfd.cn
payment:
  trade:
    host: http://trade1_9.test.91gfd.cn
accounting:
  host: http://accounting41.test.91gfd.cn
superdiamond:
  host: http://superdiamond.wangxin.test.91gfd.cn
  account:
    userCode: admin
    password: '000000'
mq:
  host: http://mq.wangxin.test.91gfd.cn
spring:
  redis:
    host: 121.43.177.8
    port: 36379
    password: Dashu0701
    timeout: 1000     #连接超时时间（毫秒）
    database: 0       #Redis数据库索引（默认为0）
    pool:
      max-active: 2   #连接池最大连接数（使用负值表示没有限制）
      max-wait: 100    #连接池最大阻塞等待时间（使用负值表示没有限制）
      max-idle: 2     #连接池中的最大空闲连接
      min-idle: 1     #连接池中的最小空闲连接